name: flutter_secure_device_id
description: A Flutter plugin for hardware-backed device identifier (Android Keystore & iOS Secure Enclave)
version: 0.3.0
homepage: https://github.com/Arokip/
repository: https://github.com/Arokip/flutter_secure_device_id/

environment:
  sdk: ^3.10.1
  flutter: '>=3.3.0'

flutter:
  plugin:
    platforms:
      android:
        package: com.com.flutter_secure_device_id
        pluginClass: FlutterSecureDeviceIdPlugin
      ios:
        pluginClass: FlutterSecureDeviceIdPlugin

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0